insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Leicester Gullick', 'Messerschmidt', '2024-12-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aharon Castelain', 'Melrose', '2002-10-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Althea Assiter', 'Lake View', '2019-07-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chicky Diver', 'Melby', '2009-05-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jackquelin Frayling', 'Bayside', '2010-01-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nell Brandsma', 'Lerdahl', '2008-09-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fayth Bratchell', '7th', '2008-07-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Roana Byham', 'Oriole', '2004-11-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Greta Killiner', 'Paget', '2020-07-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Easter Yukhnov', 'Beilfuss', '2012-06-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aurie Rangell', 'Coolidge', '2012-02-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Helena Worrall', 'Hollow Ridge', '2000-08-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Patience Szwarc', 'Farwell', '2006-12-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Yvor Raulstone', 'Hansons', '2015-06-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jackquelin Goldstone', 'Eagan', '2024-05-05');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Fidel De Few', 'Debra', '2019-11-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jessica Scorah', '4th', '2011-06-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Corabelle Tolworthie', 'Annamark', '2016-11-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Martyn Dupree', 'Artisan', '2002-11-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Audra Dufoure', 'Ohio', '2017-03-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Kenyon Tregale', 'Ridgeview', '2000-08-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Frederich Ainley', 'Mccormick', '2002-04-28');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Verla Heintsch', 'Crownhardt', '2010-07-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Humfrid Renzullo', 'Mcbride', '2003-07-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Lauren Postles', 'Corben', '2022-01-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Angelico Perritt', 'Oak Valley', '2023-12-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Edythe Reed', 'Fordem', '2023-12-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Johnna McKennan', 'Roxbury', '2022-01-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cele Edsell', 'Columbus', '2001-03-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Natalina Beentjes', 'Garrison', '2003-11-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ramona Storek', 'Kedzie', '2007-09-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Korney Bath', 'Transport', '2007-05-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Berthe Roomes', 'Jenifer', '2004-08-16');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jocko Birkenshaw', 'Cody', '2017-08-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Gladi Rymell', 'Mallory', '2019-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Broderick Pagett', 'Mccormick', '2022-03-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Candice Truitt', 'American Ash', '2008-11-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Neddie Oager', 'Tony', '2011-06-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Benjamen Hodgets', 'Forest', '2011-01-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jehu Astridge', 'Eastwood', '2021-05-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Aryn Ormshaw', 'Hollow Ridge', '2020-03-07');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Jilli Kull', 'Schurz', '2023-10-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maurise Phizacklea', 'Express', '2018-12-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Chelsey Siggens', 'Pawling', '2004-02-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Carly Heijne', 'Scott', '2013-06-12');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Orville Winfred', 'Sugar', '2018-05-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rebekah Beneyto', 'Hoard', '2019-04-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Raddie Mingame', 'Muir', '2018-07-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Judah Milborn', 'Marquette', '2014-01-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Danny Snowling', 'Rowland', '2023-05-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Poppy Jakubowicz', 'Lakeland', '2010-08-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ansel Dreye', 'Evergreen', '2002-06-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Randy Pariso', 'Rieder', '2017-05-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Genny Risbie', 'Golf Course', '2009-10-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Nalani Simonsson', 'Florence', '2013-12-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Evvie Kembry', 'Hollow Ridge', '2014-05-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Moina Girkins', 'Trailsway', '2006-02-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Georgianne Jikylls', 'Norway Maple', '2005-10-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Betteanne Lewsam', 'Grasskamp', '2011-09-15');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brucie Wilbor', 'Waxwing', '2022-03-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cristina Clubbe', 'Merry', '2013-03-21');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Orin Glanz', 'International', '2001-07-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Maddy Heigold', 'Blue Bill Park', '2018-05-22');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giraldo Ottery', 'Old Gate', '2016-09-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Hope Grane', 'Mayfield', '2002-04-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Annissa Yemm', 'Petterle', '2006-07-19');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mame Wardley', 'Sunbrook', '2015-06-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Henrik Esser', 'Welch', '2022-08-24');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Riane Laws', 'Old Shore', '2022-09-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Remington De Rechter', 'Pennsylvania', '2018-11-11');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Drew Vernau', 'Hayes', '2008-05-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Giuseppe Hugett', 'Bayside', '2013-05-30');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Anthe Sackett', 'Lighthouse Bay', '2001-07-18');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cybill Elcy', 'Elka', '2015-07-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Heywood Isack', 'Buell', '2021-11-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Ilse Spurrier', 'Oakridge', '2016-09-20');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mei Beldan', 'Ramsey', '2008-06-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Liza Tellwright', 'Carpenter', '2001-10-13');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Monroe Maddie', 'Mendota', '2005-06-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Rudyard Wederell', 'Cardinal', '2003-01-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dasie Barizeret', 'Bashford', '2012-06-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Efrem Darbon', 'Mosinee', '2004-03-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Julianna Cocklie', 'Butternut', '2002-01-31');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Zarla Clendinning', 'Maple', '2009-06-08');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bord O'' Flaherty', 'Susan', '2016-03-23');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Brandise Rylstone', 'Burning Wood', '2023-04-26');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Tasia Sorley', 'Graedel', '2023-01-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Shanna Golling', 'Gerald', '2005-04-03');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Johny Wareing', 'Independence', '2013-10-02');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Cecelia Czaja', 'Hoffman', '2002-05-17');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Glenn Fantham', 'Birchwood', '2006-10-29');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Karisa Tirte', 'Caliangt', '2003-01-14');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Sergeant Danieli', 'Vidon', '2015-05-25');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Anneliese McKeighan', 'Marquette', '2021-09-04');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Meagan Warbrick', 'Duke', '2020-03-27');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Mamie Hanster', 'Starling', '2007-09-01');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Catlee Solley', 'Warrior', '2018-05-09');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Bettine Livesey', 'Becker', '2012-10-06');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Dasha Horsewood', 'Oakridge', '2021-08-10');
insert into pasajero (nombre, direccion_residencia, fecha_nacimiento) values ('Linette De Avenell', 'Atwood', '2012-12-20');