insert into tren (modelo, capacidad) values ('Seville', 1);
insert into tren (modelo, capacidad) values ('Range Rover Sport', 2);
insert into tren (modelo, capacidad) values ('Tercel', 3);
insert into tren (modelo, capacidad) values ('Range Rover', 4);
insert into tren (modelo, capacidad) values ('Sunfire', 5);
insert into tren (modelo, capacidad) values ('Accord', 6);
insert into tren (modelo, capacidad) values ('924', 7);
insert into tren (modelo, capacidad) values ('57', 8);
insert into tren (modelo, capacidad) values ('xA', 9);
insert into tren (modelo, capacidad) values ('Skylark', 10);
insert into tren (modelo, capacidad) values ('Armada', 11);
insert into tren (modelo, capacidad) values ('Yaris', 12);
insert into tren (modelo, capacidad) values ('Elantra', 13);
insert into tren (modelo, capacidad) values ('E250', 14);
insert into tren (modelo, capacidad) values ('M6', 15);
insert into tren (modelo, capacidad) values ('Crown Victoria', 16);
insert into tren (modelo, capacidad) values ('Eurovan', 17);
insert into tren (modelo, capacidad) values ('Navigator', 18);
insert into tren (modelo, capacidad) values ('B2600', 19);
insert into tren (modelo, capacidad) values ('5 Series', 20);
insert into tren (modelo, capacidad) values ('V50', 21);
insert into tren (modelo, capacidad) values ('RAV4', 22);
insert into tren (modelo, capacidad) values ('Thunderbird', 23);
insert into tren (modelo, capacidad) values ('Swift', 24);
insert into tren (modelo, capacidad) values ('Suburban 2500', 25);
insert into tren (modelo, capacidad) values ('C-Class', 26);
insert into tren (modelo, capacidad) values ('Acclaim', 27);
insert into tren (modelo, capacidad) values ('LS', 28);
insert into tren (modelo, capacidad) values ('928', 29);
insert into tren (modelo, capacidad) values ('Ranger', 30);
insert into tren (modelo, capacidad) values ('90', 31);
insert into tren (modelo, capacidad) values ('Firebird', 32);
insert into tren (modelo, capacidad) values ('Pajero', 33);
insert into tren (modelo, capacidad) values ('164', 34);
insert into tren (modelo, capacidad) values ('Vigor', 35);
insert into tren (modelo, capacidad) values ('Electra', 36);
insert into tren (modelo, capacidad) values ('Outlander', 37);
insert into tren (modelo, capacidad) values ('Brat', 38);
insert into tren (modelo, capacidad) values ('Taurus', 39);
insert into tren (modelo, capacidad) values ('Ranger', 40);
insert into tren (modelo, capacidad) values ('1500', 41);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 42);
insert into tren (modelo, capacidad) values ('H1', 43);
insert into tren (modelo, capacidad) values ('Grand Am', 44);
insert into tren (modelo, capacidad) values ('MDX', 45);
insert into tren (modelo, capacidad) values ('Camaro', 46);
insert into tren (modelo, capacidad) values ('Th!nk', 47);
insert into tren (modelo, capacidad) values ('Escort', 48);
insert into tren (modelo, capacidad) values ('Montego', 49);
insert into tren (modelo, capacidad) values ('Sedona', 50);
insert into tren (modelo, capacidad) values ('Bonneville', 51);
insert into tren (modelo, capacidad) values ('Mustang', 52);
insert into tren (modelo, capacidad) values ('LX', 53);
insert into tren (modelo, capacidad) values ('LFA', 54);
insert into tren (modelo, capacidad) values ('Vigor', 55);
insert into tren (modelo, capacidad) values ('Probe', 56);
insert into tren (modelo, capacidad) values ('MKZ', 57);
insert into tren (modelo, capacidad) values ('Sierra 3500', 58);
insert into tren (modelo, capacidad) values ('GTO', 59);
insert into tren (modelo, capacidad) values ('Explorer Sport Trac', 60);
insert into tren (modelo, capacidad) values ('Vantage', 61);
insert into tren (modelo, capacidad) values ('9000', 62);
insert into tren (modelo, capacidad) values ('Cayman', 63);
insert into tren (modelo, capacidad) values ('Golf', 64);
insert into tren (modelo, capacidad) values ('M3', 65);
insert into tren (modelo, capacidad) values ('F350', 66);
insert into tren (modelo, capacidad) values ('Ranger', 67);
insert into tren (modelo, capacidad) values ('Riviera', 68);
insert into tren (modelo, capacidad) values ('760', 69);
insert into tren (modelo, capacidad) values ('XK Series', 70);
insert into tren (modelo, capacidad) values ('530', 71);
insert into tren (modelo, capacidad) values ('Spyder', 72);
insert into tren (modelo, capacidad) values ('B-Series', 73);
insert into tren (modelo, capacidad) values ('Discovery', 74);
insert into tren (modelo, capacidad) values ('Camry', 75);
insert into tren (modelo, capacidad) values ('Vandura 1500', 76);
insert into tren (modelo, capacidad) values ('rio', 77);
insert into tren (modelo, capacidad) values ('Justy', 78);
insert into tren (modelo, capacidad) values ('Discovery', 79);
insert into tren (modelo, capacidad) values ('Gran Sport', 80);
insert into tren (modelo, capacidad) values ('CL-Class', 81);
insert into tren (modelo, capacidad) values ('2e', 82);
insert into tren (modelo, capacidad) values ('Odyssey', 83);
insert into tren (modelo, capacidad) values ('Focus', 84);
insert into tren (modelo, capacidad) values ('Phantom', 85);
insert into tren (modelo, capacidad) values ('CLK-Class', 86);
insert into tren (modelo, capacidad) values ('Regal', 87);
insert into tren (modelo, capacidad) values ('Mighty Max', 88);
insert into tren (modelo, capacidad) values ('Genesis Coupe', 89);
insert into tren (modelo, capacidad) values ('Firebird', 90);
insert into tren (modelo, capacidad) values ('Hearse', 91);
insert into tren (modelo, capacidad) values ('Ram 3500', 92);
insert into tren (modelo, capacidad) values ('E150', 93);
insert into tren (modelo, capacidad) values ('Firebird', 94);
insert into tren (modelo, capacidad) values ('Rio5', 95);
insert into tren (modelo, capacidad) values ('Sierra 1500', 96);
insert into tren (modelo, capacidad) values ('Tracker', 97);
insert into tren (modelo, capacidad) values ('Freelander', 98);
insert into tren (modelo, capacidad) values ('Park Avenue', 99);
insert into tren (modelo, capacidad) values ('Intrepid', 100);
